const ProductData = {
  smartPhones: [
    {
      id: 1,
      name: "Apple iPhone 16 Pro Max 256GB PTA Approved",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/09/Apple-iPhone-16-Pro-cellmart-2-595x595.webp",
        "https://cellmart.pk/wp-content/uploads/2024/09/Apple-iPhone-16-Pro-max-cellmart-2.webp",
      ],
      oldPrice: 526500,
      newPrice: 489990,
      ptaApproval: "1 Year Official Warranty, Non-Active PTA Approved",
      size: "6.7 inches Dynamic AMOLED 2X Display",
      model: "Hexa-core Apple A18 Pro",
      spec: "256GB Storage, 8GB Ram",
      camera: "48MP/12MP/48MP Cameras",
      battery: "Li-Ion 4685 mAh, non-removable",
    },
    {
      id: 2,
      name: "Google Pixel 9 128GB",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/08/pixel-9-cellmart.jpg",
        "https://cellmart.pk/wp-content/uploads/2024/08/pixel-9-cellmart-1.jpg",
      ],
      oldPrice: 626500,
      newPrice: 169990,
      ptaApproval: "No Warranty (Non-PTA)",
      size: "6.3 inches LTPO OLED Display",
      model: "Octa-core Google Tensor G4",
      spec: "128GB Storage, 12GB Ram",
      camera: "50MP/10.5MP Cameras",
      battery: "4700 mAh battery",
    },
    {
      id: 3,
      name: "Google Pixel 9 Pro XL 256GB",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/08/pixel-9-pro-xl-cellmart-31.jpg",
        "https://cellmart.pk/wp-content/uploads/2024/08/pixel-9-pro-xl-cellmart-21.jpg",
      ],
      oldPrice: 426500,
      newPrice: 284990,
      ptaApproval: "No Warranty (Non-PTA)",
      size: "6.8 inches LTPO OLED Display",
      model: "Octa-core Google Tensor G4",
      spec: "256GB Storage, 16GB Ram",
      camera: "50MP 42MP Cameras",
      battery: "5060 mAh battery",
    },
    {
      id: 4,
      name: "Asus ROG Phone 9 Pro 16GB/512GB",
      images: [
        "https://cellmart.pk/wp-content/uploads/2025/01/Asus-Rog-Phone-9-pro-cellmart-1.jpg",
        "https://cellmart.pk/wp-content/uploads/2025/01/Asus-Rog-Phone-9-pro-cellmart.jpg",
      ],
      oldPrice: 746500,
      newPrice: 24990,
      ptaApproval: "No Warranty (Non-PTA)",
      size: "6.78 inches LTPO AMOLED Display",
      model: "Octa-core Snapdragon 8 Elite (3 nm)",
      spec: "512GB Storage, 16GB Ram",
      camera: "50MP/32MP Cameras",
      battery: "5800 mAh battery",
    },
    {
      id: 5,
      name: "ZTE Nubia Red Magic 10 Pro 16GB/512GB",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/11/RedMagic-10-Pro-white-cellmart.jpg",
        "https://cellmart.pk/wp-content/uploads/2024/11/RedMagic-10-Pro-black-cellmart.webp",
      ],
      oldPrice: 36500,
      newPrice: 269990,
      ptaApproval: "No Warranty (Non-PTA)",
      size: "6.85 inches AMOLED Display",
      model: "Octa-core Snapdragon 8 Elite",
      spec: "512GB Storage, 16GB Ram",
      camera: "50MP/16MP Cameras",
      battery: "6500 mAh battery",
    },
    {
      id: 6,
      name: "OnePlus 13 16GB/512GB",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/11/OnePlus-13-Black-cellmart.jpg",
        "https://cellmart.pk/wp-content/uploads/2024/11/OnePlus-13-Black-cellmart-1.jpg",
      ],
      oldPrice: 26500,
      newPrice: 257990,
      ptaApproval: "No Warranty (Non-PTA)",
      size: "6.82 inches LTPO AMOLED Display",
      model: "Octa-core Snapdragon 8 Elite (3 nm)",
      spec: "512GB Storage, 16GB Ram",
      camera: "50MP/32MP Cameras",
      battery: "Si/C 6000 mAh battery",
    },
    {
      id: 7,
      name: "Samsung Galaxy S24 FE 256GB",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/10/sam-s24-fe-blue-cellmart.jpg",
        "https://cellmart.pk/wp-content/uploads/2024/10/sam-s24-fe-mint-cellmart.jpg",
      ],
      oldPrice: 220000,
      newPrice: 205990,
      ptaApproval: "1 Year Official Warranty, Non-Active PTA Approved",
      size: "6.7 inches Dynamic AMOLED 2X Display",
      model: "Octa-core Exynos 2400e (4 nm)",
      spec: "256GB Storage, 8GB Ram",
      camera: "50MP/10MP Cameras",
      battery: "4700 mAh battery",
    },
    {
      id: 8,
      name: "Xiaomi Mix Flip 12GB/512GB",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/10/xiaomi-mix-flip-purple-cellmart.jpg",
        "https://cellmart.pk/wp-content/uploads/2024/10/xiaomi-mix-flip-black-cellmart.png",
      ],
      oldPrice: 26500,
      newPrice: 257990,
      ptaApproval: "1 Year Official Warranty, Non-Active PTA Approved",
      size: "6.82 inches LTPO AMOLED Display",
      model: "Second external AMOLED",
      spec: "512GB Storage, 12GB Ram",
      camera: "50MP/32MP Cameras",
      battery: "4780 mAh battery",
    },
  ],
  tablets: [
    {
      id: 9,
      name: "Apple iPad Pro M4 Chip 13 inches 2024 256GB WiFi",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/07/agrahihoihghiogheghios.jpg",
        "https://cellmart.pk/wp-content/uploads/2024/07/ua98ghuah8ahugihg0osegoijp.jpg",
      ],
      oldPrice: 320000,
      newPrice: 339990,
      ptaApproval: "International Warranty",
      size: "13.0 inches Ultra Retina Tandem OLED Display",
      model: "Nona-core M4",
      spec: "256GB Storage, 8GB Ram",
      camera: "12MP/12MP Cameras",
      battery: "Li-Po 10290 mAh battery",
    },
    {
      id: 10,
      name: "Apple iPad Air M2 Chip 2024 128GB WiFi 11 inches",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/07/ag98augh8ughuaogihugioahg.jpg",
        "https://cellmart.pk/wp-content/uploads/2024/07/sghoshigusegubieghiogjbsugio.jpg",
      ],
      oldPrice: 220000,
      newPrice: 178990,
      ptaApproval: "No Warranty",
      size: "11 inches Liquid Retina IPS LCD Display",
      model: "Octa-core Apple M2",
      spec: "128GB Storage, 8GB Ram",
      camera: "12MP/12MP Cameras",
      battery: "Li-Po 28.93 Wh battery",
    },
    {
      id: 11,
      name: "Samsung Galaxy Tab A9+ 4GB/64GB Wifi X210",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/07/hae8grugehg8hueagio.jpg",
        "https://cellmart.pk/wp-content/uploads/2024/07/aerg90uaighaguiip.jpg",
      ],
      oldPrice: 520000,
      newPrice: 47990,
      ptaApproval: "No Warranty",
      size: "11.0 inch TFT  LCD Display",
      model: "Octa-core Snapdragon 695 5G",
      spec: "64GB Storage, 4GB Ram",
      camera: "8MP/5MP Cameras",
      battery: "7040 mAh battery",
    },
    {
      id: 12,
      name: "Apple iPad 10 10.9 inches 2022 64GB WiFi",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/07/ipad-10-silver-cellmart.webp",
        "https://cellmart.pk/wp-content/uploads/2024/07/aiofs9gs8is8gr9ssgsu.jpg",
      ],
      oldPrice: 720000,
      newPrice: 105990,
      ptaApproval: "No Warranty",
      size: "10.9 inches Liquid Retina IPS LCD Display",
      model: "Hexa-core A14 Bionic",
      spec: "64GB Storage, 4GB Ram",
      camera: "12MP/12MP Cameras",
      battery: "28.6 Wh Battery",
    },
    {
      id: 13,
      name: "Apple iPad Mini 7 2024 128GB WiFi 8.3 inches",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/10/apple-ipad-mini-7-2024-blue-cellmart-2.jpg",
        "https://cellmart.pk/wp-content/uploads/2024/07/starlighjtjhsck.jpg",
      ],
      oldPrice: 155000,
      newPrice: 144990,
      ptaApproval: "No Warranty",
      size: "8.3 inches Liquid Retina IPS LCD",
      model: "Hexa-core Apple A17 Pro",
      spec: "128GB Storage, 8GB Ram",
      camera: "12MP/12MP Cameras",
      battery: "Li-Ion 5078 mAh",
    },
    {
      id: 14,
      name: "Samsung Galaxy Tab S9 FE WiFi X510 8GB/256GB",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/08/tab-s9-fe-cellmart.jpg",
        "https://cellmart.pk/wp-content/uploads/2024/08/tab-s9-fe-cellmart-1.jpg",
      ],
      oldPrice: 125000,
      newPrice: 103990,
      ptaApproval: "No Warranty",
      size: "11.0 inches IPS LCD, 90Hz",
      model: "Octa-core Exynos 1380 (5 nm)",
      spec: "256GB Storage, 8GB Ram",
      camera: "8MP/12MP Cameras",
      battery: "8000 mAh battery",
    },
  ],
  accessories: [
    {
      id: 15,
      name: "Apple AirPods Pro 2nd Gen",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/09/Apple-AirPods-4-cellmart.webp",
        "https://example.com/airpods-pro-back.webp",
      ],
      oldPrice: 65000,
      newPrice: 39990,
      ptaApproval: "No Warranty",
      size: "Wireless Earbuds",
      model: "H2 Chip",
      spec: "Adaptive Transparency, Spatial Audio",
      camera: "N/A",
      battery: "Up to 30 hours with charging case",
    },
    {
      id: 16,
      name: "Samsung Galaxy Buds 3 Pro",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/08/Buds-3-pro-cellmart.jpg",
        "https://example.com/airpods-pro-back.webp",
      ],
      oldPrice: 65000,
      newPrice: 44990,
      ptaApproval: "No Warranty",
      size: "Wireless Earbuds",
      model: "H2 Chip",
      spec: "Adaptive Transparency, Spatial Audio",
      camera: "N/A",
      battery: "Up to 30 hours with charging case",
    },
    {
      id: 17,
      name: "Apple 20W USB-C Power Adapter",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/07/10.jpg",
        "https://example.com/airpods-pro-back.webp",
      ],
      oldPrice: 6500,
      newPrice: 5990,
      ptaApproval: "No Warranty",
      size: "Wireless Earbuds",
      model: "H2 Chip",
      spec: "Adaptive Transparency, Spatial Audio",
      camera: "N/A",
      battery: "Up to 30 hours with charging case",
    },
    {
      id: 18,
      name: "Apple AirTag",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/07/C82.jpg",
        "https://example.com/airpods-pro-back.webp",
      ],
      oldPrice: 6500,
      newPrice: 8990,
      ptaApproval: "No Warranty",
      size: "Wireless Earbuds",
      model: "H2 Chip",
      spec: "Adaptive Transparency, Spatial Audio",
      camera: "N/A",
      battery: "Up to 30 hours with charging case",
    },
    {
      id: 19,
      name: "Apple Pencil 1st generation",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/07/18.jpg",
        "https://example.com/airpods-pro-back.webp",
      ],
      oldPrice: 4500,
      newPrice: 24990,
      ptaApproval: "No Warranty",
      size: "Wireless Earbuds",
      model: "H2 Chip",
      spec: "Adaptive Transparency, Spatial Audio",
      camera: "N/A",
      battery: "Up to 30 hours with charging case",
    },
    {
      id: 20,
      name: "USB-C to Lightning Cable",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/07/11.jpg",
        "https://example.com/airpods-pro-back.webp",
      ],
      oldPrice: 3500,
      newPrice: 2990,
      ptaApproval: "No Warranty",
      size: "Wireless Earbuds",
      model: "H2 Chip",
      spec: "Adaptive Transparency, Spatial Audio",
      camera: "N/A",
      battery: "Up to 30 hours with charging case",
    },
  ],
  trending: [
    {
      id: 21,
      name: "OnePlus 13R 12GB/256GB",
      images: [
        "https://cellmart.pk/wp-content/uploads/2025/01/OnePlus-13r-astratrail-cellmart.png",
        "https://cellmart.pk/wp-content/uploads/2025/01/OnePlus-13r-Black-cellmart.png",
      ],
      oldPrice: 180000,
      newPrice: 154990,
      ptaApproval: "No Warranty (Non-PTA)",
      size: "6.78 inches LTPO AMOLED Display",
      model: "Octa-core Snapdragon 8 Gen 3 (4 nm)",
      spec: "256GB Storage, 12GB Ram",
      camera: "50MP/16MP Cameras",
      battery: "Si/C 6000 mAh battery",
    },
    {
      id: 22,
      name: "Samsung Galaxy S25+ 12GB/256GB",
      images: [
        "https://cellmart.pk/wp-content/uploads/2025/01/sam-s25-plus-navy-cellmart.jpg",
        "https://cellmart.pk/wp-content/uploads/2025/01/sam-s25-plus-silver-cellmart.jpg",
      ],
      oldPrice: 150000,
      newPrice: 165000,
      ptaApproval: "No Warranty (Non-PTA)",
      size: "6.7 inches Dynamic LTPO AMOLED 2X Display",
      model: "Octa-core Snapdragon 8 Elite (3 nm)",
      spec: "256GB Storage, 12GB Ram",
      camera: "50MP/48MP/32MP Cameras",
      battery: "4900 mAh battery",
    },
    {
      id: 23,
      name: "Samsung Galaxy S25 Ultra 12GB/512GB",
      images: [
        "https://cellmart.pk/wp-content/uploads/2025/01/sam-s25-ultra-grey-cellmart-595x595.jpg",
        "https://cellmart.pk/wp-content/uploads/2025/01/sam-s25-ultra-black-cellmart-595x595.jpg",
      ],
      oldPrice: 200000,
      newPrice: 185000,
      ptaApproval: "1 Year Official Warranty, PTA Approved",
      size: "6.9 inches Dynamic LTPO AMOLED 2X Display",
      model: "Octa-core Snapdragon 8 Elite (3 nm)",
      spec: "512GB Storage, 12GB Ram",
      camera: "200MP/12MP Cameras",
      battery: "5000 mAh battery",
    },
    {
      id: 24,
      name: "OnePlus 13 24GB/1TB",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/11/OnePlus-13-Black-cellmart-595x595.jpg",
        "https://cellmart.pk/wp-content/uploads/2024/11/OnePlus-13-Black-cellmart-1.jpg",
      ],
      oldPrice: 180000,
      newPrice: 165000,
      ptaApproval: "No Warranty (Non-PTA)",
      size: "6.82 inches LTPO AMOLED Display",
      model: "Qualcomm Snapdragon 8 Gen 2",
      spec: "1TB Storage, 24GB Ram",
      camera: "50MP/32MP Cameras",
      battery: "Si/C 6000 mAh battery",
    },
    {
      id: 25,
      name: "ZTE Nubia Red Magic 9 Pro 12GB/256GB",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/07/gtfyygufgyutui.jpg",
        "https://cellmart.pk/wp-content/uploads/2024/07/gtfyygufgyutui.jpg",
      ],
      oldPrice: 190890,
      newPrice: 249990,
      ptaApproval: "No Warranty (Non-PTA)",
      size: "6.8 inches AMOLED Display",
      model: "Octa-core Snapdragon 8 Gen 3",
      spec: "256GB Storage, 12GB Ram",
      camera: "50MP/16MP Cameras",
      battery: "6500 mAh battery",
    },
    {
      id: 26,
      name: "Google Pixel 8 128GB",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/07/aoifhubaeghoeaughuoeaighj.jpg",
        "https://cellmart.pk/wp-content/uploads/2024/07/ushrgfosueguiseguoj.jpg",
      ],
      oldPrice: 69000,
      newPrice: 134990,
      ptaApproval: "No Warranty (Non-PTA)",
      size: "6.2 inches OLED Display",
      model: "Nona-core Tensor G3",
      spec: "128GB Storage, 8GB Ram",
      camera: "50MP/10.5MP Cameras",
      battery: "4575 mAh battery",
    },
  ],
};

export default ProductData;
