const ProductData = {
  smartPhones: [
    {
      id: 1,
      name: "Apple iPhone 16 Pro Max 256GB PTA Approved",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/09/Apple-iPhone-16-Pro-cellmart-2-595x595.webp",
        "https://cellmart.pk/wp-content/uploads/2024/09/Apple-iPhone-16-Pro-max-cellmart-2.webp",
      ],
      oldPrice: "₨ 526,500",
      newPrice: "Rs 489,990",
      ptaApproval: "1 Year Official Warranty, Non-Active PTA Approved",
      size: "6.7 inches Dynamic AMOLED 2X Display",
      model: "Hexa-core Apple A18 Pro",
      spec: "256GB Storage, 8GB Ram",
      camera: "48MP/12MP/48MP Cameras",
      battery: "Li-Ion 4685 mAh, non-removable",
    },
    {
      id: 2,
      name: "Google Pixel 9 128GB",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/08/pixel-9-cellmart.jpg",
        "https://cellmart.pk/wp-content/uploads/2024/08/pixel-9-cellmart-1.jpg",
      ],
      oldPrice: "₨ 626,500",
      newPrice: "Rs ₨ 169,990",
      ptaApproval: "No Warranty (Non-PTA)",
      size: "6.3 inches LTPO OLED Display",
      model: "Octa-core Google Tensor G4",
      spec: "128GB Storage, 12GB Ram",
      camera: "50MP/10.5MP Cameras",
      battery: "4700 mAh battery",
    },
    {
      id: 3,
      name: "Google Pixel 9 Pro XL 256GB",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/08/pixel-9-pro-xl-cellmart-31.jpg",
        "https://cellmart.pk/wp-content/uploads/2024/08/pixel-9-pro-xl-cellmart-21.jpg",
      ],
      oldPrice: "₨ 426,500",
      newPrice: "Rs 284,990",
      ptaApproval: "No Warranty (Non-PTA)",
      size: "6.8 inches LTPO OLED Display",
      model: "Octa-core Google Tensor G4",
      spec: "256GB Storage, 16GB Ram",
      camera: "50MP 42MP Cameras",
      battery: "5060 mAh battery",
    },
    {
      id: 4,
      name: "Asus ROG Phone 9 Pro 16GB/512GB",
      images: [
        "https://cellmart.pk/wp-content/uploads/2025/01/Asus-Rog-Phone-9-pro-cellmart-1.jpg",
        "https://cellmart.pk/wp-content/uploads/2025/01/Asus-Rog-Phone-9-pro-cellmart.jpg",
      ],
      oldPrice: "Rs 746,500",
      newPrice: "Rs 24,990",
      ptaApproval: "No Warranty (Non-PTA)",
      size: "6.78 inches LTPO AMOLED Display",
      model: "Octa-core Snapdragon 8 Elite (3 nm)",
      spec: "512GB Storage, 16GB Ram",
      camera: "50MP/32MP Cameras",
      battery: "5800 mAh battery",
    },
    {
      id: 5,
      name: "ZTE Nubia Red Magic 10 Pro 16GB/512GB",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/11/RedMagic-10-Pro-white-cellmart.jpg",
        "https://cellmart.pk/wp-content/uploads/2024/11/RedMagic-10-Pro-black-cellmart.webp",
      ],
      oldPrice: "Rs 36,500",
      newPrice: "Rs 269,990",
      ptaApproval: "No Warranty (Non-PTA)",
      size: "6.85 inches AMOLED Display",
      model: "Octa-core Snapdragon 8 Elite",
      spec: "512GB Storage, 16GB Ram",
      camera: "50MP/16MP Cameras",
      battery: "6500 mAh battery",
    },
    {
      id: 6,
      name: "OnePlus 13 16GB/512GB",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/11/OnePlus-13-Black-cellmart.jpg",
        "https://cellmart.pk/wp-content/uploads/2024/11/OnePlus-13-Black-cellmart-1.jpg",
      ],
      oldPrice: "Rs 26,500",
      newPrice: "Rs 257,990",
      ptaApproval: "No Warranty (Non-PTA)",
      size: "6.82 inches LTPO AMOLED Display",
      model: "Octa-core Snapdragon 8 Elite (3 nm)",
      spec: "512GB Storage, 16GB Ram",
      camera: "50MP/32MP Cameras",
      battery: "Si/C 6000 mAh battery",
    },
    {
      id: 7,
      name: "Samsung Galaxy S24 FE 256GB",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/10/sam-s24-fe-blue-cellmart.jpg",
        "https://cellmart.pk/wp-content/uploads/2024/10/sam-s24-fe-mint-cellmart.jpg",
      ],
      oldPrice: "Rs 220,000",
      newPrice: "Rs 205,990",
      ptaApproval: "1 Year Official Warranty, Non-Active PTA Approved",
      size: "6.7 inches Dynamic AMOLED 2X Display",
      model: "Octa-core Exynos 2400e (4 nm)",
      spec: "256GB Storage, 8GB Ram",
      camera: "50MP/10MP Cameras",
      battery: "4700 mAh battery",
    },
    {
      id: 8,
      name: "Xiaomi Mix Flip 12GB/512GB",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/10/xiaomi-mix-flip-purple-cellmart.jpg",
        "https://cellmart.pk/wp-content/uploads/2024/10/xiaomi-mix-flip-black-cellmart.png",
      ],
      oldPrice: "Rs 26,500",
      newPrice: "Rs 257,990",
      ptaApproval: "1 Year Official Warranty, Non-Active PTA Approved",
      size: "6.82 inches LTPO AMOLED Display",
      model: "Second external AMOLED",
      spec: "512GB Storage, 12GB Ram",
      camera: "50MP/32MP Cameras",
      battery: "4780 mAh battery",
    },
  ],
  tablets: [
    {
      id: 2,
      name: "Apple iPad Pro M4 Chip 13 inches 2024 256GB WiFi",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/07/agrahihoihghiogheghios.jpg",
        "https://cellmart.pk/wp-content/uploads/2024/07/ua98ghuah8ahugihg0osegoijp.jpg",
      ],
      oldPrice: "Rs 320,000",
      newPrice: "Rs 339,990",
      ptaApproval: "International Warranty",
      size: "13.0 inches Ultra Retina Tandem OLED Display",
      model: "Nona-core M4",
      spec: "256GB Storage, 8GB Ram",
      camera: "12MP/12MP Cameras",
      battery: "Li-Po 10290 mAh battery",
    },
    {
      id: 3,
      name: "Apple iPad Air M2 Chip 2024 128GB WiFi 11 inches",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/07/ag98augh8ughuaogihugioahg.jpg",
        "https://cellmart.pk/wp-content/uploads/2024/07/sghoshigusegubieghiogjbsugio.jpg",
      ],
      oldPrice: "Rs 220,000",
      newPrice: "Rs 178,990",
      ptaApproval: "No Warranty",
      size: "11 inches Liquid Retina IPS LCD Display",
      model: "Octa-core Apple M2",
      spec: "128GB Storage, 8GB Ram",
      camera: "12MP/12MP Cameras",
      battery: "Li-Po 28.93 Wh battery",
    },
    {
      id: 3,
      name: "Samsung Galaxy Tab A9+ 4GB/64GB Wifi X210",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/07/hae8grugehg8hueagio.jpg",
        "https://cellmart.pk/wp-content/uploads/2024/07/aerg90uaighaguiip.jpg",
      ],
      oldPrice: "Rs 520,000",
      newPrice: "Rs 47,990",
      ptaApproval: "No Warranty",
      size: "11.0 inch TFT  LCD Display",
      model: "Octa-core Snapdragon 695 5G",
      spec: "64GB Storage, 4GB Ram",
      camera: "8MP/5MP Cameras",
      battery: "7040 mAh battery",
    },
    {
      id: 4,
      name: "Apple iPad 10 10.9 inches 2022 64GB WiFi",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/07/ipad-10-silver-cellmart.webp",
        "https://cellmart.pk/wp-content/uploads/2024/07/aiofs9gs8is8gr9ssgsu.jpg",
      ],
      oldPrice: "Rs 720,000",
      newPrice: "Rs 105,990",
      ptaApproval: "No Warranty",
      size: "10.9 inches Liquid Retina IPS LCD Display",
      model: "Hexa-core A14 Bionic",
      spec: "64GB Storage, 4GB Ram",
      camera: "12MP/12MP Cameras",
      battery: "28.6 Wh Battery",
    },
    {
      id: 4,
      name: "Apple iPad Mini 7 2024 128GB WiFi 8.3 inches",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/10/apple-ipad-mini-7-2024-blue-cellmart-2.jpg",
        "https://cellmart.pk/wp-content/uploads/2024/07/starlighjtjhsck.jpg",
      ],
      oldPrice: "Rs 155,000",
      newPrice: "Rs 144,990",
      ptaApproval: "No Warranty",
      size: "8.3 inches Liquid Retina IPS LCD",
      model: "Hexa-core Apple A17 Pro",
      spec: "128GB Storage, 8GB Ram",
      camera: "12MP/12MP Cameras",
      battery: "Li-Ion 5078 mAh",
    },
    {
      id: 4,
      name: "Samsung Galaxy Tab S9 FE WiFi X510 8GB/256GB",
      images: [
        "https://cellmart.pk/wp-content/uploads/2024/08/tab-s9-fe-cellmart.jpg",
        "https://cellmart.pk/wp-content/uploads/2024/08/tab-s9-fe-cellmart-1.jpg",
      ],
      oldPrice: "Rs 125,000",
      newPrice: "Rs 103,990",
      ptaApproval: "No Warranty",
      size: "11.0 inches IPS LCD, 90Hz",
      model: "Octa-core Exynos 1380 (5 nm)",
      spec: "256GB Storage, 8GB Ram",
      camera: "8MP/12MP Cameras",
      battery: "8000 mAh battery",
    },
  ],
  accessories: [
    {
      id: 3,
      name: "Apple AirPods Pro 2nd Gen",
      images: [
        "https://example.com/airpods-pro-front.webp",
        "https://example.com/airpods-pro-back.webp",
      ],
      oldPrice: "₨ 65,000",
      newPrice: "Rs 58,500",
      ptaApproval: "Apple Original, Noise Cancellation",
      size: "Wireless Earbuds",
      model: "H2 Chip",
      spec: "Adaptive Transparency, Spatial Audio",
      camera: "N/A",
      battery: "Up to 30 hours with charging case",
    },
  ],
  trending: [
    {
      id: 4,
      name: "OnePlus 11 5G",
      images: [
        "https://example.com/oneplus11-front.webp",
        "https://example.com/oneplus11-back.webp",
      ],
      oldPrice: "₨ 180,000",
      newPrice: "Rs 165,000",
      ptaApproval: "1 Year Official Warranty, PTA Approved",
      size: "6.7 inches Fluid AMOLED",
      model: "Qualcomm Snapdragon 8 Gen 2",
      spec: "256GB Storage, 16GB Ram",
      camera: "50MP/48MP/32MP Cameras",
      battery: "Li-Po 5000 mAh, 100W Fast Charging",
    },
  ],
};

export default ProductData;
